kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: devopsbatches
spec:
  group: trainwithshubham.com
  names:
    plural: devopsbatches
    singular: devopsbatch
    kind: DevOpsBatch
    shortName:
      - junoon
      - batches
      - tws
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
               type: object


