kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager-rolebinding
  namespace: apache
subjects:
  - kind: User
    name: apache-user
    namespace: apache  # very important for ServiceAccount
roleRef:
  kind: Role
  name: apache-manager
  apiGroup: rbac.authorization.k8s.io
