kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx-replicaset
  labels:
    app: nginx
  namespace: nginx
spec:
  replicas: 7 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:  
      containers:
        - name: nginx
          image: nginx:1.21.6
          ports:
            - containerPort: 80
