apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: mongodb
spec:
  ports:
  - port: 27017
    name: mongodb
  clusterIP: None  # This makes it headless
  selector:
    app: mongodb
